data:
  builder:
    name: "src.data.associative_recall.multiquery_ar"
    kwargs:
      num_kv_pairs: 12
      train_power_a: 0.01
      test_power_a: 0.01
      random_non_queries: False
  input_seq_len: 48
  batch_size: 512

model:
  state_mixer:
    name: "torch.nn.Identity"
    kwargs: {}
  sequence_mixer:
    name: "rebased"
  d_model: 32
  num_heads: 2
  
max_epochs: 64
learning_rate: 3e-3
seed: 44
run_id: "mqar_rebased"

logger:
  project_name: "PROJECT"
  entity: "ENTITY"
  
tags: ["simple_run"]